on: [push, pull_request]
name: Python Linting
jobs:
  PythonLinting:
    name: Python linting
    runs-on: ubuntu-latest 
    steps:
        - uses: actions/checkout@v2  
        - name: Python Linter
          uses: sunnysid3up/python-linter@master
          with:
            source: "taketwo-webapi"
            strict: "medium"
            mypy-options: ""
            pylint-options: ""
            isort-options: "-w 100"
            django: false
