on: [push, pull_request]
name: Python Linting
jobs:
  PythonLinting:
    name: Python linting
    runs-on: ubuntu-latest 
    steps:
        - uses: actions/checkout@v2
          with:
              fetch-depth: 0 
        - name: Install pylint
          run: pip install pylint
        - name: Run pylint on all .py files
          run: pylint $(git ls-files '*.py')
