name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Docker Build
        run: docker build -t taketwo_api .

    - name: Docker Test
        run: |
          docker run --rm --name taketwo_api-test -d taketwo_api
          sleep 5
          STATUS_CODE=$(docker exec taketwo_api-test curl -s -o /dev/null -w "%{http_code}" localhost:8000)
          docker stop taketwo_api-test
          echo $STATUS_CODE | grep -q 200

