name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        export DB_NAME=taketwodatabase
        export DB_HOST=localhost
        export DB_PORT=5984
        export DB_USERNAME=admin
        export DB_PASSWORD=password

        docker run --rm -p 5984:5984 -d -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password couchdb
        sleep 5
        pytest taketwo-webapi


